### PR TITLE
Registering players between local connection

### LINKED ISSUE #24: Register player to GameManager on spawn
On joining the game, a player should call `GameManager.Instance.RegisterNewPlayer(localID)` in order to add them to the GameData and enable the proper UI. 

This information should be propagated across all players.

Also, this should get rid of @at669 's hardcoded player creation in GameManager's Awake().

### PR DESCRIPTION
**Pull request by at669**
Closes #24 

* Introduces (default 30s) pseudo-lobby timer once there are 2+ players joined, game auto-starts after that countdown
* Players are added upon connecting as client; base game UI enabled appropriately
* im so sorry i did not spend more time on why i couldn't network serialize a `PlayerRegisterData[]` so now i just have 4 vars and a dictionary :pensive: 
* Delete TempCharacter.cs

### CODE REVIEW

**Review by priyanka-cs — COMMENTED** [review]
nit: would it be possible to move the pseudo lobby timer to the top and have it be a different color or have a label or something? asking because I thought I broke something the first time the timer showed up in the center of the screen :sweat_smile: or we could fix it in later rounds when we polish the design too, up to you!

**Comment by at669** [comment]
> nit: would it be possible to move the pseudo lobby timer to the top and have it be a different color or have a label or something? asking because I thought I broke something the first time the timer showed up in the center of the screen sweat_smile or we could fix it in later rounds when we polish the design too, up to you!

fair point! i added some brief text to it but it certainly is not attractive UI at the moment

**Review by priyanka-cs — APPROVED** [review]
The new text is perf! Tested across 2 clients, it works great!
I think we should prob add a way to end the lobby timer if  the players are ready, but we can add it in once we start play testing!

**Comment by at669** [comment]
> The new text is perf! Tested across 2 clients, it works great! I think we should prob add a way to end the lobby timer if the players are ready, but we can add it in once we start play testing!

yeah i agree! i'm not 100% sure how multiplay ties into this part, so i was nervous about fixing this up too much--i think ideally, everyone just marks that they're ready, and the game auto-begins, but i will make a new ticket for that!

**Pull request merged**
